# alpine
FROM node:22-alpine3.19 AS builder

USER root
ENV TZ=Asia/Shanghai
RUN set -ex \
    && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories \
    && apk upgrade --no-cache --available \
    && apk add --no-cache fontconfig

