FROM node:22-alpine3.19
#FROM doc-versioning-service-node20-slim-builder:latest as runner

USER root

WORKDIR /app
COPY package.json .
COPY package-lock.json .

ARG NPM_USERNAME
ARG NPM_PASSWORD

RUN rm -f .npmrc
# node16-
#RUN echo "_auth=$(echo -n "$NPM_USERNAME:$NPM_PASSWORD" | base64)" >> ~/.npmrc

# node18+
RUN echo "//packages.aliyun.com/6393d698d690c872dceedcc0/npm/npm-registry/:_auth=$(echo -n "$NPM_USERNAME:$NPM_PASSWORD" | base64)" >> .npmrc
RUN echo "always-auth=true" >> .npmrc
RUN echo "registry=https://packages.aliyun.com/6393d698d690c872dceedcc0/npm/npm-registry/" >> .npmrc
# RUN cat .npmrc

RUN cat package.json | sed '/skia-canvas/d' > package1.json
RUN rm -f package.json
RUN mv package1.json package.json
RUN npm i

