version: '3'

services:
  kcdesign-doc-versioning-service:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
      args:
        NPM_USERNAME: ${NPM_USERNAME}
        NPM_PASSWORD: ${NPM_PASSWORD}
    image: kcdesign-doc-versioning-service:latest
    container_name: kcdesign-doc-versioning-service
    restart: always
    environment:
      TZ: Asia/Shanghai
    networks:
      coopserver_net_1:
      db_net_1:
      mongo_net_1:
    external_links:
      - db_1
      - mongo
    ports:
      - "10020:10020"
    volumes:
      - ./log:/app/dist/log

networks:
  coopserver_net_1:
  db_net_1:
    external: true
  mongo_net_1:
    external: true
