mongo:
  url: mongodb://localhost:27017
  db: kcserver

storage:
  provider: minio
  endpoint: "minio:9000"
  region: "zhuhai-1"
  accessKeyID: "T64JKDV276dJp10"
  secretAccessKey: "1JzdCtZqgiys22q"
  stsAccessKeyID: "user"
  stsSecretAccessKey: "LRfETL5HGUGAGv9"
  documentBucket: "document"

