mongo:
  url: mongodb://localhost:27017
  db: kcserver

storage:
  provider: minio
  endpoint: "localhost:9000"
  region: "zhuhai-1"
  accessKeyID: "59L3pDWuk9oLQWIgytCI"
  secretAccessKey: "GmwAzetY1L0jU4pUAqpO7RJGIsG7k3gozVH6whoJ"
  stsAccessKeyID: "user"
  stsSecretAccessKey: "GmwAzetY1L0jU4pUAqpO7RJGIsG7k3gozVH6whoJ"
  bucketName: "document"
  filesBucketName: "files"

